# Generated by Django 4.2.7 on 2023-11-25 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_address_suite_alter_address_zipcode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='catchParse',
            new_name='catchPhrase',
        ),
    ]
